version = 3.7.14
runner.dialect = scala212              # obligatoire avec scalafmt 3.x

maxColumn = 79                         # longueur max de ligne
danglingParentheses.preset = true      # syntaxe correcte pour v3.x
align.multiline = true                 # alignement de base
includeCurlyBraceInSelectChains = false
rewrite.rules = [RedundantBraces, RedundantParens]
assumeStandardLibraryStripMargin = true
spaces.inImportCurlyBraces = false
align.openParenCallSite = false
align.openParenDefnSite = false
