status = warn

# Niveau global : WARN
rootLogger.level = warn
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

# Ton package "pagerank" en DEBUG
logger.pagerank.name = pagerank
logger.pagerank.level = debug

# Réduire Spark et Hadoop
logger.spark.name = org.apache.spark
logger.spark.level = error
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

# Console appender
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c - %m%n